export const Endpoints = {
  authSync: "/auth/sync",
  authMe: "/auth/me",
  authLogout: "/auth/logout",
  authReactivate: "/auth/reactivate",
  userSettings: "/auth/me/settings",
  userAccount: "/user/account",
  userExport: "/user/export",
  billingStatus: "/billing/status",
  billingEntitlements: "/billing/entitlements",
  billingPlans: "/billing/plans",
  billingSubscribe: "/billing/razorpay/subscriptions",
  billingVerify: "/billing/razorpay/subscriptions/verify",
  billingCancel: "/billing/razorpay/subscriptions/cancel",
  supportTickets: "/support/tickets",
  supportTicketDetail: (id: string) => `/support/tickets/${id}`,
  supportTicketMessages: (id: string) => `/support/tickets/${id}/messages`,
  supportTicketClose: (id: string) => `/support/tickets/${id}/close`,
  syncStatus: "/sync/status",
  syncPush: "/sync/push",
  syncPull: "/sync/pull",
  syncData: "/sync/data",
  syncDataKey: (key: string) => `/sync/data/${key}`,
  legalDocuments: "/legal/documents",
  legalDocumentByType: (type: string) => `/legal/documents/${type}`,
  legalAccept: "/legal/accept",
  legalAcceptanceStatus: "/legal/acceptance/status",
  pushRegister: "/push/register",
  pushUnregister: "/push/unregister",
  pushPreferences: "/push/preferences",
};
